before_install:
  - cd ../..
  - mv $TRAVIS_REPO_SLUG _old
  - git config --global core.autocrlf false
  - git clone --depth=50 _old $TRAVIS_REPO_SLUG
  - cd $TRAVIS_REPO_SLUG

language: julia

sudo: false

os:
  - linux
  - osx
  - windows

arch:
  - x64
  - x86

julia:
  - 1.0
  - 1.3
  - nightly

env:
  - JULIA_PROJECT="@."

matrix:
  exclude:
    - os: osx
      arch: x86
  allow_failures:
  - julia: nightly

notifications:
  email: false

after_success:
   - julia -e 'ENV["TRAVIS_JULIA_VERSION"] == "1.3" && ENV["TRAVIS_OS_NAME"] != "linux" && exit(); using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

branches:
  only:
  - master
  - gh-pages # For building documentation
  - /^testing-.*$/ # testing branches
  - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags