name: TagBot

on:
  issue_comment:
    types:
      - created
  workflow_dispatch:

permissions: {}

concurrency:
  group: tagbot
  cancel-in-progress: false

jobs:
  TagBot:
    name: Create release tag
    permissions:
      contents: write # Create the release tag and GitHub release.
    if: github.event_name == 'workflow_dispatch' || github.actor == 'JuliaTagBot'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: JuliaRegistries/TagBot@cded32665b34ca0496d3ac10a67d08ddfc726963 # v1.25.11
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ssh: ${{ secrets.DOCUMENTER_KEY }}
